### ISSUE TITLE
This module does not work at all ?

### ISSUE THREAD

**Issue by gtao725** [conan513/mod-account-mounts#1]
Hi Conan,

I am a great fan of your work, I've recently just tried your SPP-AC repack 1.2 and found that this particular module did not work (my other characters in the same account cannot see/inherit any mounts my main character has obtained). I also tried adding this module to my original AC repack, recompiled successfully but again the module doesn't seem to do anything. Could you pls tell me if there is any "catch" to make this module work? FYI - I have of course enabled it in the conf file.

**Comment by gtao725** [comment]
any plans to make this work Conan? or has the code not being written yet?

**Comment by BarbzYHOOL** [comment]
you can't add this to a repack... you need the source

**Comment by gtao725** [comment]
> you can't add this to a repack... you need the source

I didn't just add it to repack, I of course just tried adding the source of this module to the SOURCE of azerothcore under modules folder and it compiled ok, BUT it has NO EFFECT, hence I asked Conan and to this day no reply. This is the reason I have given up on his modules (too buggy, never checked, hardly updated) and only using AzerothCore/StygianCore modules.

**Comment by BarbzYHOOL** [comment]
Yes, Conan just made these modules as a base for others to work on I guess. We have forked them officially though

Now there is a similar module that just got released, check our discord

**Comment by gtao725** [comment]
> Yes, Conan just made these modules as a base for others to work on I guess. We have forked them officially though
> 
> Now there is a similar module that just got released, check our discord

Oh thx for telling, which discord? the AzerothCore discord?

**Comment by BarbzYHOOL** [comment]
yes :)

**Comment by gtao725** [comment]
> yes :)

Great thx Barbz, I will test it tmr, already joined discord :)
